---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10000Gi
  storageClassName: "zfs-nfs"
  volumeMode: Filesystem
