---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-zfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: zfs-nfs
