---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
        - 10.43.0.0/16
        - 10.0.50.0/24
    
    auth_oidc:
      client_id: !secret oidc_client_id
      client_secret: !secret oidc_client_secret
      discovery_url: https://pid.tosih.org/.well-known/openid-configuration
  
  secrets.yaml: |
    oidc_client_id: ${OIDC_CLIENT_ID}
    oidc_client_secret: ${OIDC_CLIENT_SECRET}
