---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres/username
    - secretKey: password
      remoteRef:
        key: postgres/password
