---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname immich
  namespace: &namespace cloud
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: postgres-cluster
      namespace: databases
  interval: 1h
  path: "./kubernetes/apps/default/immich/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
