---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  interval: 1h
  chart:
    spec:
      chart: renovate
      version: 39.x
      sourceRef:
        kind: HelmRepository
        name: renovate
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cronjob:
      schedule: "0 * * * *"  # Run every hour
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 2
      concurrencyPolicy: Forbid
      
    renovate:
      config: |
        {
          "platform": "github",
          "autodiscover": false,
          "repositories": ["tosih/home-ops"],
          "onboarding": false,
          "requireConfig": "required"
        }
    
    env:
      - name: LOG_LEVEL
        value: "debug"
    
    envFrom:
      - secretRef:
          name: renovate-secret
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
    
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
          - ALL
