apiVersion: v1
kind: Secret
metadata:
  name: renovate-secret
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:a+OLnHWclcENwQEq5gucWbIhT8ZjBG7/FgA+vXX7Wwcodwl36BrDyA==,iv:ZJrMYGQOoEZ8RaljqE8lmcCSVniRrs2JYC9hrBD73rI=,tag:pIoKoCh9HOt4mfxB2MAXXw==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:m//Oqt7kq2grxPuZQyhOy8SBdXCegx1NkfPxBjkbqMzy9ckB7J6xQQ==,iv:J2twJDnnGsznxSNIUKj2Q1X+hp12NrOv3YHvNhNTNLc=,tag:0EOl2HcUCwWyv87nf/1Q+g==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdi81aGJvWnlSOHhTeDJX
        UDc3UG1VU2F6V3JxNExXZUt3QUxyTXh0NTFvCnBZT3h2Y0J1bmQxZm0yM2N5TlVL
        bDdIa0RwczdYWXI4QnAzVmdwa0JtQjgKLS0tIDVqUHBUY25DczhnR0JHQWwySHlu
        bk9OMEpGdVRzSnZWWjNpcE8zSVp4N2cK2lioFH949+KxdyeVmpWDEzFrBXBor77F
        EwbQmb2+wdG8UWaLweObSvFm/NQDJm8UPq9a9RnGA+lSAWancgJqlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T22:07:27Z"
  mac: ENC[AES256_GCM,data:2sTv224PH1B7S7egEZnh4PqfyEcDj33tSk7ZZsWqtM92VnGn18ZJssEBreshLtqfJJtP2ZKzYnU7Sg7+t8hc+Eu6YIKsDCDT/2styrc3oIbpDIQpBcfgO3t5ihtHIL2/7b/m8uD8gKDaJEfuQhKjaOUlfQcBHs28z2lvJmYMHhM=,iv:ttabjoxHFGyaNXm/bezo9QMuvVAJyw5n+NClFVxghyY=,tag:KDe/XULxhq0QJHe4d11ytQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
