# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pkxg+/reWO4+RRk4cyWBskue+QsxCfmmT3qnl76OTFnHcAYhfno32A==,iv:ymJNCaJBjFYft5FWsXySeN6ZVtAE+EEiZ34RVGOt5jA=,tag:GIfNnbphc1uz4I7V0zX/NA==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFdCT0tTUWVoY1RqRG9P
        cWVHRUdUTjVYVGVPTURoREJrbnl0ckptcm13CjhmdnAyWFVoRHJ1K2l5Sy81SUdG
        K2VOKzduSFMzOTlYZ01PendmT1dUK1kKLS0tIDFPaFNvamorOEJRTWQ0MmVZRHIz
        R0FKSUlxMWZueGt0QWxwekRjb0FKRU0KexJckPHADIASrwQfYZ36jOR4TcN+gXlt
        obEwtpLG1FkYA9wp80iCaHp+We3ymHa+fsCGp6HdX/+OOt2oJl62dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T07:15:03Z"
  mac: ENC[AES256_GCM,data:VECbsJF2r838Pzbtsjw9Rfo1VetXUlQX/BvawCMt5tpx+QSxwo8wl5BZIv8xxH6g78v5O3HOItpxYGPeMEezTTdNxr7H4Fk9ZLsfOEFXMJP+YCPci9VisT9F725tUhVXeQU490PAxoe/3cZhpNSWxAdG0VbmMW6VOU3vP4BUhaQ=,iv:SqSpSBkBmzJ9AtDFfd0Aqy32YmCumvD17jdIo2/pHmU=,tag:5tjfFHEMP9a3P+jSOaI9Zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
