# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jTynDsnQUeiMAPaYTXyFDHnH0+dUsq3YbMEj5iz754mV01o1yt7lOw==,iv:ZeDpc7aEoGmOTAUHzI4gJK8P2AQYVbH11qel70V8A98=,tag:vn85hsRq/pkgi8HdSZXBww==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTGdzVEdNbmNIZFpPWDRS
        OHR4dVhYMVRBcjU1YlhZSUFTQUNJdWhLempnCmpTdmNnYTE5NGFHZkpLTlNjS2I5
        YjdseTQ1ZU9MR29aRjh3TmJybTAxajQKLS0tIGRBV1RnbndESW9xOS8yS3o2OEFI
        V1pLZWV2dGxncWNERkxlS1pvd0c0QTAKjE2esBE+iK0YgYr5d6bURlQ5yCXDrOqV
        8fx3hGH+tLXzrju3WtKn+yb1Zy5OBCYvNiI5dJ0ro6m7Wbgj/LuVSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T06:15:44Z"
  mac: ENC[AES256_GCM,data:vfgIvlcSU7bYufCvV82t1AhlBavLKPZiwH34EkQfYRWW1OfZUbuPlLjS6Z9ltt81feYOeD4Xp3HGlfwXcBfAd/jejUv96vaI2zOdQqy3KOGEfU3YRNZIw0WDXky6IeFcybQ/nlIrVB4RDg4qE+aRZq4dCQNdCuLlRoWHqXduNb0=,iv:r0kI+L05QaOlzKHHHWUMlQ/CYyXZL+/d57EEDSKFkCo=,tag:Q5YNn6zB60SqT5sHOUCWEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
