---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 15m
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      nextcloud:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 33
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: nextcloud
              tag: 30-apache
            env:
              TZ: America/Los_Angeles
              POSTGRES_HOST: "postgres17-rw.databases.svc.cluster.local"
              POSTGRES_DB: &dbname nextcloud
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: database-nextcloud-user-nextcloud-user
                    key: LOGIN
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: database-nextcloud-user-nextcloud-user
                    key: PASSWORD
              NEXTCLOUD_ADMIN_USER: &adminuser admin
              NEXTCLOUD_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-admin-secret
                    key: NEXTCLOUD_ADMIN_PASSWORD
              NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.tosih.org"

            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /status.php
                port: 80
              readiness:
                enabled: true
                type: HTTP
                path: /status.php
                port: 80

            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 2Gi

            securityContext:
              readOnlyRootFilesystem: false

    service:
      app:
        controller: nextcloud
        type: ClusterIP
        ports:
          http:
            port: 80

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: File sync and share
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: mdi-folder-sync
          gethomepage.dev/name: Nextcloud
          gethomepage.dev/app: nextcloud
        hostnames: ["nextcloud.tosih.org"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80

    persistence:
      nextcloud:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        size: 20Gi
        globalMounts:
          - path: /var/www/html/data
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        size: 5Gi
        globalMounts:
          - path: /var/www/html/config
      custom-apps:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        size: 5Gi
        globalMounts:
          - path: /var/www/html/custom_apps
