apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-secret
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:iQFmZdhPpz8=,iv:Px3AfBBc/Ewg4ndMJPPFWBK2ElQp+ieUxhwpy9J+S3w=,tag:CelqSfiKqT5Ua7n/xW4dMw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:KK2bapEUwWs=,iv:lPyzVUw/G8xHXxUv5H8TgUWy8s8q3cb2OeBD82oBs1g=,tag:+98jCuN3QLAjpuKT+GNGWA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:6xEI/LSm2jHpBC876P5PQhJsdPw=,iv:ttds1Lhv76zLkt4j56Pa2GGuCF21ScLSRCYTnP7iBKc=,tag:8iGXKrte1o6MEuW54z0NDw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOUJ0UkRFUFBaTjAwL0tT
        L1NqajROU3c0U0hjU0JqYzZsMzJwTzgvdFE4Ck10eUFJaWxsbGZwVnlUUC9YNWx3
        b2UxbWM1M2g1a2tiYXJrQnN4NjZXYTQKLS0tIFJ5WjZCYUhVdVM2cTBBaEhPRk5V
        TXNvS1UyUmJnU1RETVIrWmhVeFBFYWMKlSontozp5CK1D/nD8kwIwrY65yxgzdVY
        ysa5F7dvd3O5OQjlYf7LXDyUz6gQikGlOBI5mqYuLb7iCH2wr1HcUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T21:12:04Z"
  mac: ENC[AES256_GCM,data:x5ImwZd+BRGz71WZssRshPxIK0xl4+oeHW/ksiv8EFW7mSMHgvSHJ5bnixRBkpPozlSFLF7G6XdzD5HvGtRWhp/oGaAPqdbOXshFhTSCkE51Z884EDV925aq/i3DmzSOLtr0WIjNSAyfsFRGSFlBqJEmvhzh+BGiol8hnhlJ3qk=,iv:3SAywR0MY8T80z82hl6gk9wHP/vd0Po0j4fxwliPCEs=,tag:x2GGGqN5F6CMR4yWkFhaHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
