---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres/username
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: postgres/password
