# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:N5ijl2blQ62TVReQkzJeJphyx64CfbH+gOVLk2hQH/Y=,iv:o0XqHFl6AXQw+GbFNr8ASuPBjpHlUBu80tWF8pVsuz8=,tag:jYUY5LjQqzkhO30amkt4PA==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZKy92SStmVmxyR1BLN3gy
        WEk0K3RwejZYcjFDWEs0Y0xNdjFMMmlGMDJBCjkxblFNYzZLOUM5elJDdXRINEZL
        aWczTTQ3NFdKSXJnY25VcGFhMVlVQlkKLS0tIFlpbWdCMi9pckI5a2hraXJrQ3kx
        YWd5S1daUWR5b2l6d3lxU1RSVTV0ZUkKMjMQNYHSb9xcUcPTPY8auSdyst4gHeAm
        39sDHGuKm9j6jvpj1K+ERcCRXZI0BFJwFkZoOaNUhRleHiqnuZoKVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T07:15:03Z"
  mac: ENC[AES256_GCM,data:N67fLY+bJPgZwFpfy/5Rp1vvvoioeVYPAlmwvmXKJD4wIXZiJ0H5LsIdzdJcphFpRJug4bdF9aWQHb4P9nO4i9zWc4gfde34udCYU7WulcTSyCE78SQiZP6kTu7YQKYHkNaUaI1CiZlKFGRDfsS7XYvvHeb2VX3kPrHOafyEido=,iv:WDkv/CV/bjpgnoYr+NbvY/Vbm4q7apS4q69zTN0SR/M=,tag:kiE87Amm360noIFAsZp1Qw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
