# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:VethSzBX1Md5htw1bAzSKWlO7kDknuHGCJqSjGsAlnk=,iv:6tMbSXbMU46+Zjy6jckF88BI9fyq1+GYdRFeDYPAHSo=,tag:bwbTzOXUx9FG32zSnpJcMw==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdnZLc3E3ajhJTkcvZEUy
        Z1FHY1VUV3R2dHQ3d3dSMjNJTE9RdXlFMzFFCjI4WmFTdXFVZGNMTEZDS3lNUW5P
        MlVkV1JtTndMTXhxN1R4VTdob3JpRmMKLS0tIFI2RkZoWEdjU1FFNFZscDRGYjhN
        a2hEUDZxY3JGRURqcWpaUVFEdlRvY0UKq4eHVXAqvdTdrWy/Su6cSnpgPJA+RK2s
        yQJgehiNoSW73I1AJgM0dtPYwl064FuV3T58aJYfp5GRAPF3ngtTLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T06:15:44Z"
  mac: ENC[AES256_GCM,data:UCEGa8rV4HZ4aJY6gELUb3hW9vIEuOCU0B4a2+ma5q3FV++1dn8wiryUOZXu6mL+qPKGuW9isH4TPNAslc1e5vom6cSAFN5rlOHHWuGXihhbm+S+zkV+zItB5PzA33gyn4MU/K19c43x/LvE2RjG7dDbLNK/BITSGAp90e55auA=,iv:5kILnautzBeammxoJsyiC/hxcg29WkR9rruJK1dOEyE=,tag:s6IiLIyDFtoHmuNPfuz8XA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
