# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6quX5RXjAdt8ZJW813pDZw+iyoH2UmI0zHuLxo0kflU=,iv:28kQ3fbJc2UcGLtzM9ypJWvwp9+xrKB4vEXdiJ2hxp4=,tag:zSbuT2pjQYXY8AY3XHkfAw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa210cXhBVFc1dFJod2d1
        bEpWSk1GNzNCdlowMWN1ZDB1OXZuZjJPK0YwCkpHWmZ6ZGUyOWJleVNLOW1Ybm9s
        RnBNOWZ0c0R4SFRxeXRjWHJsLy9NYzgKLS0tIGlrbGVuTjM4Y0ZkR0xacXBYUGo2
        ZHI1UTZpTVNVQ3pCRWtiTW5RcnJURVEKFxMZwdIP4h5i1ZRSHA/F52yZ9ZttjchE
        u9vlx6KuxNtVUxUQP0iDylLXzjqz0auuoc3f6MkUVka8m5gc0BkFGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T22:21:41Z"
  mac: ENC[AES256_GCM,data:t0B3T0X7/UhYwaSSBGOOHJuoW+Yxzd3qHluydIiXAdyS8XrQs13jrlKufV5ldlAXp00UCVJ0kJh8wBNj4rYR8PrPTc3GT/51JinVM5wAm+8d9D+AKJQHHzgb8anqcTUh7/lmI9MYY2xaYnLeNJ+sgLCsXcp5nI4IzRDXzgYA5D0=,iv:MnxcvniKv08OBMGTOE3f7AFzyY9RDCNmBPvgP2ryJ7c=,tag:OVPru4j+mnP3Bai8egVMuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
