---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - ./cloudnative-pg/ks.yaml
  - ./dragonfly/ks.yaml
  - ./ext-postgres-operator/ks.yaml
  - ./vernemq/ks.yaml
components:
  - ../../components/common
