# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GDaz4697gTo2wPEZ3Zj9Lkl62WnGEtLrUg9jYkrQ1YLgLzZnWKSiIZ6gKkpTX9QBwSqv0Vjl+BLDka8COawDtlm1nozixa8H3rHEtZ79b9S9FCZdyU4w8mAB2N38VBWJJEYtCdyACqjbBxfkYjJSa1/FAHRzmpDOLN0ZB+XI4RkoNLn5AakR4Y2B9rpYLjSmT2Xibb7fdB8xbGs0rLUTZPbAG+jILjdn5af2/FXai8mcrU71,iv:dUbadW+l5seP+Dhxiw0eicSMLnoUvSDEnuclCZvc53U=,tag:lmhTWTALoqLKq70C+9medA==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WU01UHg4MFN6aTUvdXFM
        OEFyOUJPNDdYZkNDYTBEKzlBUUx3Z0ttZXhVCkcxOGlDWkpUbS9Hamk3dC9vRGtH
        d2JJalJxbUVoRVNybm5YSys2dVhQT3cKLS0tIExiMWlNQmFmSnlLU0pUUXNCMnM1
        MmhwQU14SnpHVVFJMmZ2UWMvY0RQVmsKUWiSK4iYYfYfRf7PBjMLtwWRGTKXPMII
        sJJWDxn/fX9rUe0t9yC4fwBJwsPRebEADqvkzKCp1RY5Ej2RWrbeuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T22:21:42Z"
  mac: ENC[AES256_GCM,data:gnmjKdRAAc4dRYl9+txNb1ySrmhpqW4K9OWg+AHKYP1M41OOHzlw5nKHf2lub/YW2aIt9nGnJuMoRuLGK4Jc1epMuuWnJ1dc3oO0OtiaNExj767XnwcappK4+98H5kT3QJ6r/uDRZRawazCpvCtlOAqZUwdE9gVbPMGd7kRfJFw=,iv:POnxcTCMsH8rE7En93rdWHniw9pXh0lRZ6R1o0hxdnw=,tag:XeBznoLJ/u+pCIJLO+363g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
