# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:roL8KDsx+rFyn/V57/R12bGwpufRaEXuP7jvIcRDy7sWfZA4+WTAmtKBCunR8VsU5tKg0SINlP/zMPzQzKSMtxjufeubYUrMQJ7iSl4wbH1mRp2WSuLBllXUXku4IPf1JpBb0s9sQfOXmG8sNaqOfG496KjJkkABxYhaaDBmSqFq9OpHDsVlLPliA63V089gJJFqhKCza3LHgWKjxqA1rm7yjCDpDv1bkcQYVTxAS7POqbDG,iv:++eBaolB5l1KA31wYqBrs6Lbzpwgkzxqor69+uCL0bU=,tag:eDSnQl6N5tSTBFp23tYBcQ==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVpvSGUxM3hrdXV3azk4
        OFlZNlNqbjFUazY5RFpIbHpkQWxoVHlLUkRrClo5YjNmYXRBVWZ2Mk9qaWkwTDlE
        Y0F1cG4zZ2NFeEZLZllxaVBDQjBncVkKLS0tIDA3UU1PeDBzYUJqaDh6b1dpOXI3
        ZXRiZEpEQ2pSMDY2eVQxT2daU3BkcTgK5ooRQIJPscFCND0VAvjAtEzPO/Qu7Ljr
        JdIAdTK4JhCM1+ZpujI45oiQe1WzMOLaNLIsgCgzUL3pJ0TGVmz72A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T06:15:44Z"
  mac: ENC[AES256_GCM,data:jlLljEqcdL+Oly8yC59ctWOuFlTy+gZ78ggjdxgD/ARGyJIMFpFyAAkrn1ANFKluJC0qFWNdYoXbyHKmMVrKMxYCEyESjcRyCiu7/cfQe2N5Oug+3MBDWlrXBmQSHBQZm+tc4T+xYopRKdw62SKP/TC2EzfKH6A8TlJ2pMXcz74=,iv:7yBCM23swh+6VHxMfze1ENnz+fxeAl919+vKP2aoSRg=,tag:IIA3J5EMef/UetkRWiS6VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
