# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:y4DeXP+6rY3arKh3ThyRe2JLFbHZfPPJH0sfTMkn8wF6Z3CKezKMfaL8upt7bgAGZw4Nse5aA94KGlI91c6EKHtaRbeclN5+TLPfpV43gqC4iBNBrDUFUwgNovwdcTSkMJAxOO//ksfI968n/0O2uVLW5j8xVp3n3diHkLMtP1WTN6XIYPup91mbDnzbzJv71uisRqC7/J/wy1xTDs1XLt8ue8+XSdZHOKpJXyfg6UxH8CK3,iv:Ne3+G03regAxnh5LdakVk8h53x3ANrqCLy2Fiu+uYfg=,tag:A0dntQ8j8Ldf4p+hegEDVw==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaVNmY0FQZGg4akk3bGsz
        NmtqYTJQSGpnVitCWUVibEZ4ZlVaZm0xRng4CmRGR2hBc2lxS2RXYi96cGMzMW9S
        MWFnY3kxck1zRVpwZ3FKVnNNdXc4ZmcKLS0tIEk2SC9ORDdNZFVnaDJhTUZGUjhC
        NlVKYlFDOFNsdUNsZWZ1U3VSM2kyekkKbh0gA8XbWChVxjqf2Si01HvPrk/Ec0Rt
        zG+7yH6vllhvFuTTw76Yqq2Xe9OPhAdW8MhOTXQAJJ8rZ2wj7QeDFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T07:15:03Z"
  mac: ENC[AES256_GCM,data:M7cASZl1kHYh8/xzmBdcoYDHoDFOOxMDBdnzPPxLjGwEfnFz13i3kMRtpBoHMrQzY9SLpQek9h5NxMdRnxOUx7c1eDtPXXlbmo8fRHBnaoeTH9K3xAysU0KznZSpLvQx2cLtXjKMoIt+w44BYPdi/RH4qPYyU5aiGE2AyNbRzQU=,iv:zuRFTSQKBruDa24Oss3rjYAO0EgK3jKOmXM7eQKqZsM=,tag:xegOfJrBS8VqAjl2/mFNJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
