# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:oZ4qf0xV56QxuIlcfutlZ0H33O/o+48dkl5iVaxZA6MTAIb3JjkX8WuE9Y/r+L1KiZ1OsPwFOkBMIwBF/tCeuyClp9ysQasETyE1R06a5yRjltCS9hkOCiP+Hy2LUF/Ppz0BG62+jI8PKKWwrM38mkrkH+a9kYiEJ0lATtHTMochkgVRsjNZA2/ptch6Ti5jAobovo8JB8A/z768KFj1COK4SaeKdN+PMy5s+ROM/XsOiWYZ,iv:VkNFLWCttcUqOktq4ZoXQjd4I8Kqlq+p5+2jLT60AH8=,tag:T+KSS+7H0wDhkSM5jAMp5w==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ek5nVDBhSU9Bb1BpNUN0
        cU5FampIMENROW9wbVdyWDE3ck5qS25JZjFRCjdtcU95OU1KN251UGxjUHNCQmxW
        a25ucFlncU5sZnFUcmNEQjd6WThoaGMKLS0tIDY1dmhLa0F0dzRkVUNrem83V2ZQ
        Q1liVGJYZWVoZnoxUkxIYzZSVHVwSjgKYzJ1oZ4r7oDKapqrvxftN8CrjPabrhnd
        FkVITUaOOuJBlDPBZ6MbsSQFFrkBFhXq561kNbBwYGUtOKlpYMa9cA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-29T04:10:05Z"
  mac: ENC[AES256_GCM,data:knHJkzc6YWMwG4tK6Gw0bXdFoHcdzh42rACfXJ3UHcqp8HqcMM3IJxxhkRmk+JE+drsYeK3q6blKEeCWJa9wvs/bqvnvOVK2LRAqZU85ORagb1Nr8UMGDr373kehGEDAFmPByAlm87g0krM6vXYNbMPVpmBqd68oz3WemCXauvc=,iv:cRWxTnFIE6leIpsQAKJ3BwAc5Zmsz/F24pfhG/hGk1c=,tag:y68OQFPu8jVG0b7pkRfVAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
