---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
  namespace: home
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      scrypted:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.142.7-noble-full
            env:
              SCRYPTED_SECURE_PORT: &secure 11443
            resources:
              requests:
                cpu: 136m
                memory: 1Gi
              limits:
                memory: 3Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        type: NodePort
        ports:
          http:
            port: &http 11080
            nodePort: 31080
          https:
            port: *secure
            nodePort: 31443
          rebroadcast:
            port: 34135
            nodePort: 34135
    route:
      app:
        enabled: true
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        hostnames: ["scrypted.tosih.org"]
        rules:
          - backendRefs:
              - identifier: app
                port: *http
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: zfs-nfs
        size: 10Gi
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
