# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0R2HRY4UcnasSCVLK9X9y1GTWrgPzor0sYw+tDdD9q23fm2dic0M0Q==,iv:OLqfSUzkzQH8fFHpwds3BMlDxuqxdbSncQ5NwCutnFM=,tag:pJJGk6d02uV5Fl+8gqzPFA==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaUtTSFRWK0ZlSTMyMVJk
        YTN0ZzdURzNpMzNHKzdjQ1lETEpnNXdGejNBCnFHQXFORmdmODErcFB6RC9HdHIz
        VjZhRFMzbkZFWGl4eXI4OW5Uc3BKeEkKLS0tIDYvbHdSdDJKbTVwVnBwTWtFUDR5
        VUw4N0R5Nlk1VENKR1lValREZktXbDQKdeVVOxOx03kxNYK4fGmZV1V3+ivD3fcX
        beGfj72Vj3NqsC/SrImXJ1tc3brSb6RVAxUDI2ItlxBty358PftNzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T22:21:41Z"
  mac: ENC[AES256_GCM,data:NpBgYgBdm7T6s014/LZoB1Kks34zf00IzUYbLmRRTzYuus+Qix5xGZNgseeZSmraNJrAyX+S/9G+0PMVfjmGJ4wGGONj5S4WdJw/5jg4aCN4NKL2GHJp6hhMoi0yoMAluYgJA6ufa0US6cdGTBJ7in+etu8JpRCLwTsb0igroEs=,iv:ORVhgPR7NAf5LdrJ1RruBKn4V1p2di/AYkzdv+KWE30=,tag:mbqrqWmDFZaB7/jVglaHgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
