# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:K7GMS77Bvi9TSs0YAeMnUyPvcXt+39m3CIziowMGqOxgOKBt+C0mZA==,iv:DPcnZnDMb1pgoVw4LYJGaujX/dcmeiJUpb3cjfDd0JU=,tag:hyyEZ/254OZR3CYxvUF82w==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZE5RN2haNVF4RkVONit1
        THUvY2JrRGVMeHdTRGx0bWVRcDdITnJza0U4CkpnalFjTk9xb3NmUTE3K1o4NHBj
        ZWEzK0Z6VDZ6amNmaGVpVFQyS1VlOE0KLS0tIEtiVUVoSkIwODNXVllSNkNkVHYw
        UUQ5OGFKU0xNMmptdUszUmRwOEFXUU0KoSS6yUccoatijx1fhAmNIHHiIalr1m51
        fGQY6yWANx1ByT/ti0oxQuCIlwzB9ELWReDIblKWEZ3iacWauV1SJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T06:15:44Z"
  mac: ENC[AES256_GCM,data:hD/SHZMEMjGQ4g4qcOwMEQGHNc6S59hBoF26L0HjLCqk8/kQ9O2ydlZleBdb0QEOqWVMXzoX690oGtcTsV35+gLX5MrFM9hhf1jSGwxQ9AOd9WTPiG6V+wk1ZigtVR0tIr4mjWcfe91rgi2vsKk0ebqAoJuFMkBHxgiBl9SsWf8=,iv:KqO9+UT+0Nry5E2B6dim+lZh2+HuEsm0bJO7q3szfzw=,tag:dTq++A/FUguMisMmMR2nbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
