---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
