apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-secret
  namespace: cloud
stringData:
  FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:cBMTSDDaVWw=,iv:tAj5xXv556Ra2MFwcVlvVMOi398EH9eivQRXZVuHXxg=,tag:JlLNsS47N3gbkTvZCPgHmQ==,type:str]
  FILEBROWSER_JWT_TOKEN_SECRET: ENC[AES256_GCM,data:6a6QmabW0xm3U+lE8JWqNEEy6A==,iv:L9Sdni6qs7yVAQYZtCltdkdDV01w0ffXgElUXAyJpCM=,tag:NUu5SumbSNQB91aOywqlpw==,type:str]
  FILEBROWSER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:M9+xBUglgPzj+O7bpGKCR9gan9rrc0eieFxy9Y3C7SV8nVYn,iv:+7ce7yIPXrkc3kdUpsRHiWbQLYdHwZ4tCixwXnAvzKI=,tag:OWqjrXP/uGwe+D91CIH/gw==,type:str]
  FILEBROWSER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Pv2rttClNfF+/z1wSTvWhnqXc5hjWKftsQRwSuiKWr0=,iv:OmnNffbkZAviS3K4IeDVklD+kWWLW6xbZZHgH22Ktlk=,tag:c5sg3bYGhmNw7WRS/K4yHw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU3JjSXFUZU94cktTM0JG
        SC9iTTNDdFMzMHdvWGR3azQybW9lbzVNSmhnCmMwT0ZNNUFTRmJhdlBLcU9ONC9u
        bzF2TUE4S3czQ1Zxb2l2VHRZOWFNeXcKLS0tIDluN2h2NklCUlI5VE1LNVBnNDJ1
        WDViYlZHZ3JVdnNEbDIzSDlMTGRSZTgK//Lx5UdDYwIadF1KavSX0U9yrPm972SP
        LstljXkBBSXvMv+s/8bKiwS6UiBrVkGkh8y5kw9qaDKgVF5OVLwk8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T21:48:25Z"
  mac: ENC[AES256_GCM,data:2mZu2HcE++0crWG62+G3KKcVVbzFcxxDhJ8467rbdepiq7eGFwT78J8/rrThLSDjroW/JGpX1fVilTNH3a9uabvPTqlT9X5DWJf2OP83SxtMWiC+5k99k61Hkwqs/lENqwtWTYEfGL7FJfXLR0b6dkul3FrpLqhDom2tGM3QjFM=,iv:atQnJFvANGQevp8SjplbmiFZC+XkjeT0/Oi7tIUHvvE=,tag:nZ/3Ce+qE1+UEildVX8Niw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
