apiVersion: v1
kind: Secret
metadata:
  name: filebrowser-secret
  namespace: cloud
stringData:
  FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:cBMTSDDaVWw=,iv:tAj5xXv556Ra2MFwcVlvVMOi398EH9eivQRXZVuHXxg=,tag:JlLNsS47N3gbkTvZCPgHmQ==,type:str]
  FILEBROWSER_JWT_TOKEN_SECRET: ENC[AES256_GCM,data:6a6QmabW0xm3U+lE8JWqNEEy6A==,iv:L9Sdni6qs7yVAQYZtCltdkdDV01w0ffXgElUXAyJpCM=,tag:NUu5SumbSNQB91aOywqlpw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU3JjSXFUZU94cktTM0JG
        SC9iTTNDdFMzMHdvWGR3azQybW9lbzVNSmhnCmMwT0ZNNUFTRmJhdlBLcU9ONC9u
        bzF2TUE4S3czQ1Zxb2l2VHRZOWFNeXcKLS0tIDluN2h2NklCUlI5VE1LNVBnNDJ1
        WDViYlZHZ3JVdnNEbDIzSDlMTGRSZTgK//Lx5UdDYwIadF1KavSX0U9yrPm972SP
        LstljXkBBSXvMv+s/8bKiwS6UiBrVkGkh8y5kw9qaDKgVF5OVLwk8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T21:25:54Z"
  mac: ENC[AES256_GCM,data:+7JGqetlj7Gsie+UHMXOGRbcCUCOCz+2gSj3Mo7Akbxbxvvcpj1fKw4BAkDH8gBrZGB1DpellcNvDZRPAKpE3pxlrXMP/UMoyPkBB9bbLBcWXf47lgTBz2ut8TQ9vYZmH3J7GaD7dzd3SGW7G8U4KLforkgXdtGMn9HB+bMBtTw=,iv:PgidnlaPgQuJYRtrbMdIAdOdszmrXLGVjHceIe2ZtnA=,tag:1fxfkxrLeVP7c/DB6tg9sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
