apiVersion: v1
kind: Secret
metadata:
  name: unifi-network-application-mongo-secret
  namespace: network
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:sguIY08=,iv:4XmgGv+xS2DBsHkCygN5FQ3kpCw5iEgLbXaeOzuw7yk=,tag:zZRQuB98ikrTOkexdwM13A==,type:str]
  MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:bxqod53cAPF2Nm3g4mHdBSmPWat63t2pM6UPigNKL2I=,iv:F1DwGPxzpvKMX0sWX2SoMSGjs/RSc0jY4bnSshrxEDY=,tag:Z+DhtqI/da3miybKJT3gAA==,type:str]
  MONGO_USER: ENC[AES256_GCM,data:rslxPw0=,iv:cgxGiV9/PScuu6DqezjOKZW7uNNfTiuvCX5LutC7Ryc=,tag:HwoOrTX2NT28sPt5qy8Zug==,type:str]
  MONGO_PASS: ENC[AES256_GCM,data:p1Szol7ZmlQqZzvujRiZtbV9v9/lm4qumIN9oFShz8E=,iv:n1mCEQpKn9Cq/XcZwQ8F7/1/Db2oECN+cwmqpS+wxew=,tag:CBUMcPzbDJ9uH7YfNd3gQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMXZVUHJRZFFQM2xGWUx2
        SGg1bUF1VzFYK09DWmRPNHg4STROcE1US2drCm9HdlBGK2lLbVI1UU50Q2NNdU1J
        KzJFbEM1RGlobWJjR1V0OTB0V0hWYkEKLS0tIHM2UmpsN25GTGVlVVIxai81Mnhq
        MlBTWUx4YkdnZlpwMEJVRlYyZ1NTaWcK3M26mLRdHjYfbofC4/zA9L/kO2+JIbLt
        kMeuQRCpu/nSGrXSVy54N0MWWM9hnHimViejHSm5CPu/x9H8Q9zhxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-03T04:24:08Z"
  mac: ENC[AES256_GCM,data:jmYNC+IasVKEdxQk8gtOBjG6ET5IZcm1rJuqjNW0hjDyO5zW7g3Txf76psDzdrEzG/sn5FbGuFSPTWorrToZPB72ChpUsBDL6DOLCFSqfgyiicqsezLJuP4Jm/VuYPPjHCdl+zxYq3HY2ST4jNIOSk7szcAGzlKZn7oJJnnPe2A=,iv:A7dRFw8tlXJKgL0yUgOcYQmYd1Qhw989m+R95btsQyg=,tag:gEE48zjGE1eFQkBocu89dQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
