---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-network-application-config-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-network-application-mongodb-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
