---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud-init
spec:
  refreshInterval: 1h
  target:
    name: opencloud-init-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        # Random secrets (32 chars alphanumeric)
        jwtSecret: "{{ .jwtSecret }}"
        machineAuthApiKey: "{{ .machineAuthApiKey }}"
        transferSecret: "{{ .transferSecret }}"
        serviceAccountSecret: "{{ .serviceAccountSecret }}"
        idmServicePassword: "{{ .idmServicePassword }}"
        idmRevaServicePassword: "{{ .idmRevaServicePassword }}"
        idmIdpServicePassword: "{{ .idmIdpServicePassword }}"
        collaborationWopiSecret: "{{ .collaborationWopiSecret }}"
        systemUserApiKey: "{{ .systemUserApiKey }}"
        urlSigningSecret: "{{ .urlSigningSecret }}"
        thumbnailsTransferSecret: "{{ .thumbnailsTransferSecret }}"
        IDM_ADMIN_PASSWORD: "{{ .idmAdminPassword }}"
        # UUIDs
        systemUserID: "{{ .systemUserID }}"
        adminUserID: "{{ .adminUserID }}"
        serviceAccountID: "{{ .serviceAccountID }}"
        graphApplicationID: "{{ .graphApplicationID }}"
        storageUsersMountID: "{{ .storageUsersMountID }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: opencloud-init-secrets
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: opencloud-init-uuids
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: opencloud-init-secrets
spec:
  length: 32
  digits: 10
  symbols: 0
  symbolCharacters: ""
  noUpper: false
  allowRepeat: true
  spec:
    - key: jwtSecret
    - key: machineAuthApiKey
    - key: transferSecret
    - key: serviceAccountSecret
    - key: idmServicePassword
    - key: idmRevaServicePassword
    - key: idmIdpServicePassword
    - key: collaborationWopiSecret
    - key: systemUserApiKey
    - key: urlSigningSecret
    - key: thumbnailsTransferSecret
    - key: idmAdminPassword
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: UUID
metadata:
  name: opencloud-init-uuids
spec:
  spec:
    - key: systemUserID
    - key: adminUserID
    - key: serviceAccountID
    - key: graphApplicationID
    - key: storageUsersMountID
