apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
  namespace: cloud
stringData:
  WEB_OIDC_CLIENT_ID: ENC[AES256_GCM,data:j8THW0RzY11ifxMfa9EW1CAbVXW/5psljMmmUt+oPfvur/C1,iv:EFP5XlbKdBKtDR8PhoQsJYjWao7gWQPPJ2t5XXv5Pik=,tag:LmrVBp+NcPQOrXylvFh0IA==,type:str]
  WEB_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:His0DsvrODxgu3o1LpsmA0aPGcVW+y4s8Sz/l8+okR4=,iv:kQ8vp9W1kPEqdMyMDY9/0ROnGDMSxGvHcAwjayGr0vI=,tag:hyccTHbTFEbjtp0WGasgKg==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S2J3OENkelZxUmpNbWlM
        c0pqM2tpeDVwcUZQa3VxdmhtWU1wa2lVc0JVCjgrNy9tWmpacjBJcjdPRjUwKzla
        UG5xTnZJaS8zT3A5OFRKMVAyTXUwOTQKLS0tIHNSTk9lTWFRRFo4YXdmT2I0c0Mr
        LzBoVGhIbERhU2xQdFZRY25XeTFjRUEKz7ZxpbTgENbvu43/03zUODVI/71i5lp2
        cAoa5Oc83NEzutY+tV7bvMkyJons59Em3fQgvPKOO93ED5i+AW6DVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T05:58:46Z"
  mac: ENC[AES256_GCM,data:YzFMQZkWxp6uvtHCE2rFVYn2bdX7uiyLMHUcetgCGK4/qdKvdkqX6qhV09fJQ5gIsbpPUMYiXeesXSjZgzIuAnMzcoPaDyfq0iCLYZwIffY+Hs5YhYFMtKRCbwAmSY+7VDDjA7GZ0irl+fwKZciY8OELAx9vC9uHYx+fhgjrGFE=,iv:TPV6txdPcsmrd4BecDp1k/cjWx0OFeDqdyW+hoWLc34=,tag:tJvuuWX3Z5qZ31hhw7Y8VA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
