apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
  namespace: cloud
stringData:
  WEB_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:2x/IsrGdByQpUUCFLzQ3MBt/JbOtLg==,iv:abav7e/je9d09qprwM6bdtjvutARzRmW3QzMJfj/b3A=,tag:X674LlO8O/hA45boMAfvzw==,type:str]
  IDM_ADMIN_PASSWORD: ENC[AES256_GCM,data:E358aqT7X1E=,iv:YOyWqav0Gia3eDRKuIe9MveefnVmP5RYQYB+TCvgyfM=,tag:jZKOWFtiGAjjzufj5fVVqg==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S2J3OENkelZxUmpNbWlM
        c0pqM2tpeDVwcUZQa3VxdmhtWU1wa2lVc0JVCjgrNy9tWmpacjBJcjdPRjUwKzla
        UG5xTnZJaS8zT3A5OFRKMVAyTXUwOTQKLS0tIHNSTk9lTWFRRFo4YXdmT2I0c0Mr
        LzBoVGhIbERhU2xQdFZRY25XeTFjRUEKz7ZxpbTgENbvu43/03zUODVI/71i5lp2
        cAoa5Oc83NEzutY+tV7bvMkyJons59Em3fQgvPKOO93ED5i+AW6DVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T02:27:06Z"
  mac: ENC[AES256_GCM,data:4FlciHVu9zazW9GT4AUwBU8KgeOHSCLL4MSh1hsJWLhI9LVAl1UP0OqreHnaDWCCW28MoxGzYSDC+Jir0WhJjdLOJ4qrxv4NLf4VPGJnbGdbFlamJwcrRDdMDkKQrSTMQF9H1n9hU0Reg8mcz4eHKyW0sUuHxQL3SU/XxuIR9TY=,iv:XexxeRWbA66+rbghSi3jdrNoy1lwao/D4XzQYwX0Uxk=,tag:jqyU+Yy406Y5+ZMTMfL9WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
