---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname home-assistant
  namespace: &namespace home
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: vernemq
      namespace: databases
    - name: postgres-cluster
      namespace: databases
  interval: 1h
  path: "./kubernetes/apps/home/home-assistant/app"
  postBuild:
    substitute:
      APP: *appname
      APP_GID: "0"
      APP_UID: "0"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
