apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0ah1GMcKRXK6,iv:QXZEBEcnk3OceyvAnfcWtjkvLGic5/Fpqt/Ldp/FjTU=,tag:JLfxCG5COJK8cqwiFlc3GQ==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdGhTL0hIeXk4c3NhMTJN
        L3RwSFpQclVhSnY4aHMxeTBSZ3lYYmRZT21BCnowQTRMSDlpczM5TUNYU3AzMGxj
        R09iRUJDK1BwWlNpalZaeWpsLzh2OFUKLS0tIDZ1UURoUmVLd0hkaUMxci9PaWMx
        RWdlL1FRQ1VjdnZQamNIc3c1aXF1VkkKuUTTUjc8mSmyaNEwa5KZewRDHTPXWJLq
        vgvtnzu9IHtwWblOSCXlmNxpdrjYWL7Kj07JxEvPGOnpy1TgQ/efIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T07:15:03Z"
  mac: ENC[AES256_GCM,data:knToo3wY8XBxA4qeW4udTDkvW2mQjES0pCwZUNLPAOmUkpHE3TdJZ6UpxQaAH/K88BNouYZmT8TG2a2mbyEiG+kK2+R/6Ll8rgRAT/EeiWA/KKFMDrgaxgSvYF55camXdtu4F/nORKDAj01i5/QMVgt7IUs8byV2h5EGkmer9wM=,iv:VwTW5GM7OeaJWjYflZ8Hnw9AyGb7WiGCHDXD+ng1zJ0=,tag:fM7rngYQPH9g5amYlkVciw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
