apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PYFiNIN/EpGq,iv:sBJ8tWNZGrYs+5hIj8gEqGXerDh9CWelgNej8dfdGZQ=,tag:dqpsOe3tB3Tt9xQXBJkQBw==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb2dsQmRVSTNXQzJ2Nmdr
        WE5XSEh4V0ZpMFVzczQwdkVyT3VNemhHeXowCk1IaGFvbXJzWTVHQzBldGh5TFBl
        TkNFZ0w0d3Fsa0FtbUdlY0ZvYWtsZDgKLS0tIHRabDArT0hqWEFJVlppNEdlUmZW
        aDl2elNyOGgwMVN0QUJKc08xbmpUam8KmEQ2wTZ9dmYn7ma3UIbgy/lkJcBnak29
        A6UjoIIHyNRNNCY90vEMk9BaujrW2ANYATBqE45k+9M24x4DbBEcYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T06:15:44Z"
  mac: ENC[AES256_GCM,data:D4O2oCvDsITJX4Ma0VvT3mJjzl6kj1bG+kHbBe9edtdbIBPptly+A68wdhMDg0TLeaHomNsUr2fQcUnE69vxYeem3d5ww26ad3nR/Sdw/8ZH4Q+6I6aBTpnWL/Ezvk/NnSWrXP+2klLGpg6Lrq/02mNcHBVUmno7xIovNh+QjrY=,iv:pJH6PuZwwryLkfhlq9R1WhM5uQJsYznRCSYGZpqp6qQ=,tag:R3ypIfzwGmMEwuzHFUdkpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
