apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:aHWH/qVoizBj,iv:Y/GYRnXCABbYyx7rwFJzW8Ssi+MGAGTfsMPtmeOYVLI=,tag:WS2peoZSLQSUUpgL0poq+w==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK1h4Mk92dHlJajN2TGpi
        emVrWThOM3d4TFRrYXdNOGtSQlpIWHBvUVdzCkJSZUlQaG5aRlh5S015Q2doK2Nm
        Y2UzMlVPYjJLelR3ZVRrdTJ5aldRaEEKLS0tIHAzUmdNa2p5aW1RV3hOQy9MeTJz
        aEtjWVlHek9TcDZLTVNsYkZzK2swd3cKAaFHH33rm8H58N9QrC9PonM/Txi2AqVp
        kYY6bonjne1+gnVYeJ36RQd8aDIAq1M0nlwi0oEhZwAV6xUriM80yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-29T04:10:04Z"
  mac: ENC[AES256_GCM,data:QKojHnvlrFVfEVytzKC/Lfx2YWBMFbT1usVuO9qgaa6azuEvWmxWhVc3okNLgNymBOpaW++0JP6cUpmFB/6j/FwY6EY4XHFceR7S//gzoUgiq8HgtzHpYRyV1VkYnx/cu1RDKuRrvogDCoFtUN0SYgieuZ84pO3/OEYGJo8zTO4=,iv:WbTwfvzVVczwnss8Qu5Xsr/8NBG8unBMT+hE7sL8qOw=,tag:8O1RHmgaHPksOdQfwm4oZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
