apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:B7buFI/wdWny,iv:B8HCBEGD3nWUatiLKTDLPpQpjsXh3scEF9LJNmWqreg=,tag:O1+kfpmhZo2/f9xyDw7+BQ==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RzdVSTZFRHBLeDVVNlEx
        M2FhSGdoczVIN1RUdnAwZC9EL09aT3F3S1VNCjFZTFZDb05FS1prVVpXNE9aV1Ex
        VnVwR2lNT0JLejNnb1o1Y1BsK0JZTjAKLS0tIEFZaS83SmlrVXEvNGRNRHhCSllK
        WGpZVkNtVU02WEp0bjVYaFJBT2VyN0UKp+pXmZ+VBlg0iu4P+0CNkzTaKE8eBMn3
        tGaQmgheaVg6RvwCBXzQh7+MSrfitLXdJ6XBYL482MjfgAp1YVyX6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T22:21:41Z"
  mac: ENC[AES256_GCM,data:9bBvnodMC4OTQOpaCbUTtoZh9IymiPW7Mqx4ai5fI4+tZTohptknfUOio5jyk7u0keOHuT9mbJ/+eAiCcrmxQxIDNrkOag3roMbze+DWq+jXbKqn/ow7gSWtXyg5km4n93Aymj8m6TYzX6hUT6RJOj3gb5zt+FYbYTJ/1yDFiIQ=,iv:eWgkoT0AgqOjXKcE8myD3H+264PKD+GraamK6h4MAxM=,tag:TFE/8pGG4sLeqkKJtwGlHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
