apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:eFdn69F316HV1sYTiuMBjHOXc+emN2vgeW6UJ0oR17uReuy/MTGTVOyEAnTwboCxNV+hrtZKDBOKcyulq6QUUmLXM/Qw9OuC+Og=,iv:zNmPP+8WM1Q3LcSdVOHXKh722hex4dd6n9+qs6hWna0=,tag:tMfhyZkSIuSbPAvAzBYFkg==,type:str]
sops:
  age:
    - recipient: age12dke0my8ykaja7psstd3mxqrt2rjdxhst3d2pqea2gw04feqv9gqqccshq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bDhCUmpaTmhwNWFjZ2Jj
        SUxvMC9KaG1ETHdVSWJqYkxvSFpoOE15MkhBCjdhdzB2RXVQbUNtQnpva3Y4NWd0
        NHhnMk9WUnNTZHFlcnl5QUFmd1haS2MKLS0tIE91L1ZsbGdjUVB0NFg3ZjlYbytR
        NXZHMnBVd2g5WXVaaGRYZ3BaYXdwdkEKa5FpOm6BfJkCqgMmJZbCqYtkPWHl8MKU
        j7eQzzO/RbZl0gZbD9YEm0kOzVwPo8KI3R6WAKkFh7xzaadtl2GGRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-14T07:15:03Z"
  mac: ENC[AES256_GCM,data:k9VEmcZDPkePIjc6q/2lkymh3P8hB4vra9frqdXCqtCXyocrWUzJ15JZKgztCKSA1NKeMVc5YmELcLlk6tlmjKC78be1qN+NTFGD7V3otHJLC7AezzFmDUfTeDxKlWjssHcUS04CeWUlzhBrxv4tIVpN0EfHyC8VqjBB8F1uIsM=,iv:uHwnD3RDdc3izzP6BYv3Q5Etf8xZgvTvfDJJNIJ2TYk=,tag:eObWW3ggDm7ERxmtwqYLjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
