---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-longhorn
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
