---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname pocket-id
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1h
  path: ./kubernetes/apps/security/pocket-id/app
  postBuild:
    substitute:
      APP: *appname
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
