---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencloud
  namespace: cloud
spec:
  targetNamespace: cloud
  commonMetadata:
    labels:
      app.kubernetes.io/name: opencloud
  path: ./kubernetes/apps/cloud/opencloud/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
