---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-secrets
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    replicaCount: 2
    leaderElect: true
    image:
      repository: ghcr.io/external-secrets/external-secrets
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
