---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vernemq-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: vernemq-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: DOCKER_VERNEMQ_USER_admin
      remoteRef:
        key: mqtt/admin_password
    - secretKey: DOCKER_VERNEMQ_USER_mqtt
      remoteRef:
        key: mqtt/password
    - secretKey: DOCKER_VERNEMQ_DISTRIBUTED_COOKIE
      remoteRef:
        key: mqtt/vernemq_cookie
